// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// clogit_loglik_cpp
Rcpp::NumericVector clogit_loglik_cpp(const arma::mat& X, const arma::ivec& chosen, const arma::vec& offset, const arma::ivec& group_start, const arma::ivec& group_size, int max_iter, double tol);
RcppExport SEXP _fastclogit_clogit_loglik_cpp(SEXP XSEXP, SEXP chosenSEXP, SEXP offsetSEXP, SEXP group_startSEXP, SEXP group_sizeSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type chosen(chosenSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type group_start(group_startSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type group_size(group_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(clogit_loglik_cpp(X, chosen, offset, group_start, group_size, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// clogit_fit_cpp
Rcpp::List clogit_fit_cpp(const arma::mat& X, const arma::ivec& chosen, const arma::vec& offset, const arma::ivec& group_start, const arma::ivec& group_size, int max_iter, double tol, bool verbose);
RcppExport SEXP _fastclogit_clogit_fit_cpp(SEXP XSEXP, SEXP chosenSEXP, SEXP offsetSEXP, SEXP group_startSEXP, SEXP group_sizeSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type chosen(chosenSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type group_start(group_startSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type group_size(group_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(clogit_fit_cpp(X, chosen, offset, group_start, group_size, max_iter, tol, verbose));
    return rcpp_result_gen;
END_RCPP
}
// clogit_fit_sparse_cpp
Rcpp::List clogit_fit_sparse_cpp(const arma::sp_mat& X_csc, const arma::ivec& chosen, const arma::vec& offset, const arma::ivec& group_start, const arma::ivec& group_size, int max_iter, double tol, bool verbose);
RcppExport SEXP _fastclogit_clogit_fit_sparse_cpp(SEXP X_cscSEXP, SEXP chosenSEXP, SEXP offsetSEXP, SEXP group_startSEXP, SEXP group_sizeSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type X_csc(X_cscSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type chosen(chosenSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type group_start(group_startSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type group_size(group_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(clogit_fit_sparse_cpp(X_csc, chosen, offset, group_start, group_size, max_iter, tol, verbose));
    return rcpp_result_gen;
END_RCPP
}
// clogit_sandwich_cpp
Rcpp::List clogit_sandwich_cpp(const arma::mat& X, const arma::ivec& chosen, const arma::vec& offset, const arma::ivec& group_start, const arma::ivec& group_size, const arma::ivec& cluster_id, const arma::vec& beta, const arma::mat& hess_inv);
RcppExport SEXP _fastclogit_clogit_sandwich_cpp(SEXP XSEXP, SEXP chosenSEXP, SEXP offsetSEXP, SEXP group_startSEXP, SEXP group_sizeSEXP, SEXP cluster_idSEXP, SEXP betaSEXP, SEXP hess_invSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type chosen(chosenSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type group_start(group_startSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type group_size(group_sizeSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type cluster_id(cluster_idSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type hess_inv(hess_invSEXP);
    rcpp_result_gen = Rcpp::wrap(clogit_sandwich_cpp(X, chosen, offset, group_start, group_size, cluster_id, beta, hess_inv));
    return rcpp_result_gen;
END_RCPP
}
// clogit_sandwich_sparse_cpp
Rcpp::List clogit_sandwich_sparse_cpp(const arma::sp_mat& X_csc, const arma::ivec& chosen, const arma::vec& offset, const arma::ivec& group_start, const arma::ivec& group_size, const arma::ivec& cluster_id, const arma::vec& beta, const arma::mat& hess_inv);
RcppExport SEXP _fastclogit_clogit_sandwich_sparse_cpp(SEXP X_cscSEXP, SEXP chosenSEXP, SEXP offsetSEXP, SEXP group_startSEXP, SEXP group_sizeSEXP, SEXP cluster_idSEXP, SEXP betaSEXP, SEXP hess_invSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type X_csc(X_cscSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type chosen(chosenSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type group_start(group_startSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type group_size(group_sizeSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type cluster_id(cluster_idSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type hess_inv(hess_invSEXP);
    rcpp_result_gen = Rcpp::wrap(clogit_sandwich_sparse_cpp(X_csc, chosen, offset, group_start, group_size, cluster_id, beta, hess_inv));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastclogit_clogit_loglik_cpp", (DL_FUNC) &_fastclogit_clogit_loglik_cpp, 7},
    {"_fastclogit_clogit_fit_cpp", (DL_FUNC) &_fastclogit_clogit_fit_cpp, 8},
    {"_fastclogit_clogit_fit_sparse_cpp", (DL_FUNC) &_fastclogit_clogit_fit_sparse_cpp, 8},
    {"_fastclogit_clogit_sandwich_cpp", (DL_FUNC) &_fastclogit_clogit_sandwich_cpp, 8},
    {"_fastclogit_clogit_sandwich_sparse_cpp", (DL_FUNC) &_fastclogit_clogit_sandwich_sparse_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastclogit(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
