# Generated by Rcpp — do not edit by hand

#' @useDynLib fastclogit, .registration = TRUE
#' @importFrom Rcpp sourceCpp
NULL

clogit_fit_cpp <- function(X, chosen, offset, group_start, group_size, max_iter, tol, verbose) {
    .Call(`_fastclogit_clogit_fit_cpp`, X, chosen, offset, group_start, group_size, max_iter, tol, verbose)
}

clogit_sandwich_cpp <- function(X, chosen, offset, group_start, group_size, cluster_id, beta, hess_inv) {
    .Call(`_fastclogit_clogit_sandwich_cpp`, X, chosen, offset, group_start, group_size, cluster_id, beta, hess_inv)
}
